services:
- type: pserv
  name: mysql
  plan: starter-plus
  env: docker
  region: frankfurt
  autoDeploy: true
  disk:
    name: mysql
    mountPath: /var/lib/mysql
    sizeGB: 10
  envVars:
  - fromGroup: mysql

envVarGroups:
- name: mysql
  envVars:
  - key: MYSQL_DATABASE
    value: mydatabase
  - key: MYSQL_USER
    value: myuser
  - key: MYSQL_PASSWORD
    generateValue: true
  - key: MYSQL_ROOT_PASSWORD
    generateValue: true
